name=input("Enter the name")
city=input("Enter the city")
street=input("Enter the street")
pinNum=input("Enter the pin number")
houseNum=input("Enter the house number")
print("Mailing address is:")
print(name)
print(city)
print(street)
print(pinNum)
print(houseNum)